-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vec_vec_op_streaming_vector_add2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    vec1_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    vec1_TVALID : IN STD_LOGIC;
    vec1_TREADY : OUT STD_LOGIC;
    vec1_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
    vec1_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
    vec1_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    vec1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    vec1_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    vec1_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    vec2_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    vec2_TVALID : IN STD_LOGIC;
    vec2_TREADY : OUT STD_LOGIC;
    vec2_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
    vec2_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
    vec2_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    vec2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    vec2_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    vec2_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    vec_out_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    vec_out_TVALID : OUT STD_LOGIC;
    vec_out_TREADY : IN STD_LOGIC;
    vec_out_TKEEP : OUT STD_LOGIC_VECTOR (15 downto 0);
    vec_out_TSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    vec_out_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
    vec_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    vec_out_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    vec_out_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of vec_vec_op_streaming_vector_add2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_57 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010111";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_68 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_78 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal vec1_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln118_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal vec2_TDATA_blk_n : STD_LOGIC;
    signal vec_out_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal icmp_ln118_reg_684 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_reg_199 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln118_fu_210_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ref_tmp_keep_reg_688 : STD_LOGIC_VECTOR (15 downto 0);
    signal ref_tmp_strb_reg_693 : STD_LOGIC_VECTOR (15 downto 0);
    signal ref_tmp_user_reg_698 : STD_LOGIC_VECTOR (1 downto 0);
    signal ref_tmp_last_reg_703 : STD_LOGIC_VECTOR (0 downto 0);
    signal ref_tmp_id_reg_708 : STD_LOGIC_VECTOR (4 downto 0);
    signal ref_tmp_dest_reg_713 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln126_fu_562_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_reg_718 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_1_fu_568_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_1_reg_723 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_2_fu_574_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_2_reg_728 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_3_fu_580_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_3_reg_733 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_4_fu_586_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_4_reg_738 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_5_fu_592_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_5_reg_743 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_6_fu_598_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_6_reg_748 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_7_fu_604_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_7_reg_753 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_8_fu_610_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_8_reg_758 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_9_fu_616_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_9_reg_763 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_10_fu_622_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_10_reg_768 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_11_fu_628_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_11_reg_773 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_12_fu_634_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_12_reg_778 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_13_fu_640_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_13_reg_783 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_14_fu_646_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_14_reg_788 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_15_fu_652_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln126_15_reg_793 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln120_fu_250_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_fu_408_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_1_fu_254_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_1_fu_412_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_2_fu_264_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_2_fu_422_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_3_fu_274_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_3_fu_432_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_4_fu_284_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_4_fu_442_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_5_fu_294_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_5_fu_452_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_6_fu_304_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_6_fu_462_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_7_fu_314_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_7_fu_472_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_8_fu_324_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_8_fu_482_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_9_fu_334_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_9_fu_492_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_s_fu_344_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_s_fu_502_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_10_fu_354_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_10_fu_512_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_11_fu_364_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_11_fu_522_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_12_fu_374_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_12_fu_532_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_13_fu_384_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_13_fu_542_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln120_14_fu_394_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln121_14_fu_552_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    j_reg_199_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                j_reg_199 <= ap_const_lv2_0;
            elsif (((icmp_ln118_fu_216_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j_reg_199 <= add_ln118_fu_210_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln118_fu_216_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln126_10_reg_768 <= add_ln126_10_fu_622_p2;
                add_ln126_11_reg_773 <= add_ln126_11_fu_628_p2;
                add_ln126_12_reg_778 <= add_ln126_12_fu_634_p2;
                add_ln126_13_reg_783 <= add_ln126_13_fu_640_p2;
                add_ln126_14_reg_788 <= add_ln126_14_fu_646_p2;
                add_ln126_15_reg_793 <= add_ln126_15_fu_652_p2;
                add_ln126_1_reg_723 <= add_ln126_1_fu_568_p2;
                add_ln126_2_reg_728 <= add_ln126_2_fu_574_p2;
                add_ln126_3_reg_733 <= add_ln126_3_fu_580_p2;
                add_ln126_4_reg_738 <= add_ln126_4_fu_586_p2;
                add_ln126_5_reg_743 <= add_ln126_5_fu_592_p2;
                add_ln126_6_reg_748 <= add_ln126_6_fu_598_p2;
                add_ln126_7_reg_753 <= add_ln126_7_fu_604_p2;
                add_ln126_8_reg_758 <= add_ln126_8_fu_610_p2;
                add_ln126_9_reg_763 <= add_ln126_9_fu_616_p2;
                add_ln126_reg_718 <= add_ln126_fu_562_p2;
                ref_tmp_dest_reg_713 <= vec1_TDEST;
                ref_tmp_id_reg_708 <= vec1_TID;
                ref_tmp_keep_reg_688 <= vec1_TKEEP;
                ref_tmp_last_reg_703 <= vec1_TLAST;
                ref_tmp_strb_reg_693 <= vec1_TSTRB;
                ref_tmp_user_reg_698 <= vec1_TUSER;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln118_reg_684 <= icmp_ln118_fu_216_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter0, icmp_ln118_fu_216_p2, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((icmp_ln118_fu_216_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((icmp_ln118_fu_216_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln118_fu_210_p2 <= std_logic_vector(unsigned(j_reg_199) + unsigned(ap_const_lv2_1));
    add_ln126_10_fu_622_p2 <= std_logic_vector(unsigned(trunc_ln120_s_fu_344_p4) + unsigned(trunc_ln121_s_fu_502_p4));
    add_ln126_11_fu_628_p2 <= std_logic_vector(unsigned(trunc_ln120_10_fu_354_p4) + unsigned(trunc_ln121_10_fu_512_p4));
    add_ln126_12_fu_634_p2 <= std_logic_vector(unsigned(trunc_ln120_11_fu_364_p4) + unsigned(trunc_ln121_11_fu_522_p4));
    add_ln126_13_fu_640_p2 <= std_logic_vector(unsigned(trunc_ln120_12_fu_374_p4) + unsigned(trunc_ln121_12_fu_532_p4));
    add_ln126_14_fu_646_p2 <= std_logic_vector(unsigned(trunc_ln120_13_fu_384_p4) + unsigned(trunc_ln121_13_fu_542_p4));
    add_ln126_15_fu_652_p2 <= std_logic_vector(unsigned(trunc_ln120_14_fu_394_p4) + unsigned(trunc_ln121_14_fu_552_p4));
    add_ln126_1_fu_568_p2 <= std_logic_vector(unsigned(trunc_ln120_1_fu_254_p4) + unsigned(trunc_ln121_1_fu_412_p4));
    add_ln126_2_fu_574_p2 <= std_logic_vector(unsigned(trunc_ln120_2_fu_264_p4) + unsigned(trunc_ln121_2_fu_422_p4));
    add_ln126_3_fu_580_p2 <= std_logic_vector(unsigned(trunc_ln120_3_fu_274_p4) + unsigned(trunc_ln121_3_fu_432_p4));
    add_ln126_4_fu_586_p2 <= std_logic_vector(unsigned(trunc_ln120_4_fu_284_p4) + unsigned(trunc_ln121_4_fu_442_p4));
    add_ln126_5_fu_592_p2 <= std_logic_vector(unsigned(trunc_ln120_5_fu_294_p4) + unsigned(trunc_ln121_5_fu_452_p4));
    add_ln126_6_fu_598_p2 <= std_logic_vector(unsigned(trunc_ln120_6_fu_304_p4) + unsigned(trunc_ln121_6_fu_462_p4));
    add_ln126_7_fu_604_p2 <= std_logic_vector(unsigned(trunc_ln120_7_fu_314_p4) + unsigned(trunc_ln121_7_fu_472_p4));
    add_ln126_8_fu_610_p2 <= std_logic_vector(unsigned(trunc_ln120_8_fu_324_p4) + unsigned(trunc_ln121_8_fu_482_p4));
    add_ln126_9_fu_616_p2 <= std_logic_vector(unsigned(trunc_ln120_9_fu_334_p4) + unsigned(trunc_ln121_9_fu_492_p4));
    add_ln126_fu_562_p2 <= std_logic_vector(unsigned(trunc_ln120_fu_250_p1) + unsigned(trunc_ln121_fu_408_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(vec1_TVALID, vec2_TVALID, vec_out_TREADY, ap_enable_reg_pp0_iter0, icmp_ln118_fu_216_p2, ap_enable_reg_pp0_iter1, icmp_ln118_reg_684)
    begin
                ap_block_pp0_stage0_01001 <= (((icmp_ln118_reg_684 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (vec_out_TREADY = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (((icmp_ln118_fu_216_p2 = ap_const_lv1_0) and (vec2_TVALID = ap_const_logic_0)) or ((icmp_ln118_fu_216_p2 = ap_const_lv1_0) and (vec1_TVALID = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(vec1_TVALID, vec2_TVALID, vec_out_TREADY, ap_enable_reg_pp0_iter0, icmp_ln118_fu_216_p2, ap_enable_reg_pp0_iter1, icmp_ln118_reg_684, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln118_reg_684 = ap_const_lv1_0) and (vec_out_TREADY = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (((icmp_ln118_fu_216_p2 = ap_const_lv1_0) and (vec2_TVALID = ap_const_logic_0)) or ((icmp_ln118_fu_216_p2 = ap_const_lv1_0) and (vec1_TVALID = ap_const_logic_0)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(vec1_TVALID, vec2_TVALID, vec_out_TREADY, ap_enable_reg_pp0_iter0, icmp_ln118_fu_216_p2, ap_enable_reg_pp0_iter1, icmp_ln118_reg_684, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln118_reg_684 = ap_const_lv1_0) and (vec_out_TREADY = ap_const_logic_0)))) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (((icmp_ln118_fu_216_p2 = ap_const_lv1_0) and (vec2_TVALID = ap_const_logic_0)) or ((icmp_ln118_fu_216_p2 = ap_const_lv1_0) and (vec1_TVALID = ap_const_logic_0)))));
    end process;


    ap_block_state2_pp0_stage0_iter0_assign_proc : process(vec1_TVALID, vec2_TVALID, icmp_ln118_fu_216_p2)
    begin
                ap_block_state2_pp0_stage0_iter0 <= (((icmp_ln118_fu_216_p2 = ap_const_lv1_0) and (vec2_TVALID = ap_const_logic_0)) or ((icmp_ln118_fu_216_p2 = ap_const_lv1_0) and (vec1_TVALID = ap_const_logic_0)));
    end process;


    ap_block_state3_io_assign_proc : process(vec_out_TREADY, icmp_ln118_reg_684)
    begin
                ap_block_state3_io <= ((icmp_ln118_reg_684 = ap_const_lv1_0) and (vec_out_TREADY = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter1_assign_proc : process(vec_out_TREADY, icmp_ln118_reg_684)
    begin
                ap_block_state3_pp0_stage0_iter1 <= ((icmp_ln118_reg_684 = ap_const_lv1_0) and (vec_out_TREADY = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln118_fu_216_p2)
    begin
        if ((icmp_ln118_fu_216_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln118_fu_216_p2 <= "1" when (j_reg_199 = ap_const_lv2_3) else "0";
    trunc_ln120_10_fu_354_p4 <= vec1_TDATA(95 downto 88);
    trunc_ln120_11_fu_364_p4 <= vec1_TDATA(103 downto 96);
    trunc_ln120_12_fu_374_p4 <= vec1_TDATA(111 downto 104);
    trunc_ln120_13_fu_384_p4 <= vec1_TDATA(119 downto 112);
    trunc_ln120_14_fu_394_p4 <= vec1_TDATA(127 downto 120);
    trunc_ln120_1_fu_254_p4 <= vec1_TDATA(15 downto 8);
    trunc_ln120_2_fu_264_p4 <= vec1_TDATA(23 downto 16);
    trunc_ln120_3_fu_274_p4 <= vec1_TDATA(31 downto 24);
    trunc_ln120_4_fu_284_p4 <= vec1_TDATA(39 downto 32);
    trunc_ln120_5_fu_294_p4 <= vec1_TDATA(47 downto 40);
    trunc_ln120_6_fu_304_p4 <= vec1_TDATA(55 downto 48);
    trunc_ln120_7_fu_314_p4 <= vec1_TDATA(63 downto 56);
    trunc_ln120_8_fu_324_p4 <= vec1_TDATA(71 downto 64);
    trunc_ln120_9_fu_334_p4 <= vec1_TDATA(79 downto 72);
    trunc_ln120_fu_250_p1 <= vec1_TDATA(8 - 1 downto 0);
    trunc_ln120_s_fu_344_p4 <= vec1_TDATA(87 downto 80);
    trunc_ln121_10_fu_512_p4 <= vec2_TDATA(95 downto 88);
    trunc_ln121_11_fu_522_p4 <= vec2_TDATA(103 downto 96);
    trunc_ln121_12_fu_532_p4 <= vec2_TDATA(111 downto 104);
    trunc_ln121_13_fu_542_p4 <= vec2_TDATA(119 downto 112);
    trunc_ln121_14_fu_552_p4 <= vec2_TDATA(127 downto 120);
    trunc_ln121_1_fu_412_p4 <= vec2_TDATA(15 downto 8);
    trunc_ln121_2_fu_422_p4 <= vec2_TDATA(23 downto 16);
    trunc_ln121_3_fu_432_p4 <= vec2_TDATA(31 downto 24);
    trunc_ln121_4_fu_442_p4 <= vec2_TDATA(39 downto 32);
    trunc_ln121_5_fu_452_p4 <= vec2_TDATA(47 downto 40);
    trunc_ln121_6_fu_462_p4 <= vec2_TDATA(55 downto 48);
    trunc_ln121_7_fu_472_p4 <= vec2_TDATA(63 downto 56);
    trunc_ln121_8_fu_482_p4 <= vec2_TDATA(71 downto 64);
    trunc_ln121_9_fu_492_p4 <= vec2_TDATA(79 downto 72);
    trunc_ln121_fu_408_p1 <= vec2_TDATA(8 - 1 downto 0);
    trunc_ln121_s_fu_502_p4 <= vec2_TDATA(87 downto 80);

    vec1_TDATA_blk_n_assign_proc : process(vec1_TVALID, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln118_fu_216_p2)
    begin
        if (((icmp_ln118_fu_216_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            vec1_TDATA_blk_n <= vec1_TVALID;
        else 
            vec1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    vec1_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln118_fu_216_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln118_fu_216_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            vec1_TREADY <= ap_const_logic_1;
        else 
            vec1_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    vec2_TDATA_blk_n_assign_proc : process(vec2_TVALID, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, icmp_ln118_fu_216_p2)
    begin
        if (((icmp_ln118_fu_216_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            vec2_TDATA_blk_n <= vec2_TVALID;
        else 
            vec2_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    vec2_TREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln118_fu_216_p2, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln118_fu_216_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            vec2_TREADY <= ap_const_logic_1;
        else 
            vec2_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    vec_out_TDATA <= (((((((((((((((add_ln126_15_reg_793 & add_ln126_14_reg_788) & add_ln126_13_reg_783) & add_ln126_12_reg_778) & add_ln126_11_reg_773) & add_ln126_10_reg_768) & add_ln126_9_reg_763) & add_ln126_8_reg_758) & add_ln126_7_reg_753) & add_ln126_6_reg_748) & add_ln126_5_reg_743) & add_ln126_4_reg_738) & add_ln126_3_reg_733) & add_ln126_2_reg_728) & add_ln126_1_reg_723) & add_ln126_reg_718);

    vec_out_TDATA_blk_n_assign_proc : process(vec_out_TREADY, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln118_reg_684)
    begin
        if (((icmp_ln118_reg_684 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            vec_out_TDATA_blk_n <= vec_out_TREADY;
        else 
            vec_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    vec_out_TDEST <= ref_tmp_dest_reg_713;
    vec_out_TID <= ref_tmp_id_reg_708;
    vec_out_TKEEP <= ref_tmp_keep_reg_688;
    vec_out_TLAST <= ref_tmp_last_reg_703;
    vec_out_TSTRB <= ref_tmp_strb_reg_693;
    vec_out_TUSER <= ref_tmp_user_reg_698;

    vec_out_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln118_reg_684, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln118_reg_684 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            vec_out_TVALID <= ap_const_logic_1;
        else 
            vec_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

end behav;
