-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity vec_vec_op_streaming is
generic (
    C_S_AXI_BUS_A_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_BUS_A_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    vec1_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    vec1_TVALID : IN STD_LOGIC;
    vec1_TREADY : OUT STD_LOGIC;
    vec1_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
    vec1_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
    vec1_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    vec1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    vec1_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    vec1_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    vec2_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    vec2_TVALID : IN STD_LOGIC;
    vec2_TREADY : OUT STD_LOGIC;
    vec2_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
    vec2_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
    vec2_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    vec2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    vec2_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    vec2_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    vec_out_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    vec_out_TVALID : OUT STD_LOGIC;
    vec_out_TREADY : IN STD_LOGIC;
    vec_out_TKEEP : OUT STD_LOGIC_VECTOR (15 downto 0);
    vec_out_TSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
    vec_out_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
    vec_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    vec_out_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    vec_out_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0);
    s_axi_BUS_A_AWVALID : IN STD_LOGIC;
    s_axi_BUS_A_AWREADY : OUT STD_LOGIC;
    s_axi_BUS_A_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_ADDR_WIDTH-1 downto 0);
    s_axi_BUS_A_WVALID : IN STD_LOGIC;
    s_axi_BUS_A_WREADY : OUT STD_LOGIC;
    s_axi_BUS_A_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_DATA_WIDTH-1 downto 0);
    s_axi_BUS_A_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_DATA_WIDTH/8-1 downto 0);
    s_axi_BUS_A_ARVALID : IN STD_LOGIC;
    s_axi_BUS_A_ARREADY : OUT STD_LOGIC;
    s_axi_BUS_A_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_ADDR_WIDTH-1 downto 0);
    s_axi_BUS_A_RVALID : OUT STD_LOGIC;
    s_axi_BUS_A_RREADY : IN STD_LOGIC;
    s_axi_BUS_A_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_BUS_A_DATA_WIDTH-1 downto 0);
    s_axi_BUS_A_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_BUS_A_BVALID : OUT STD_LOGIC;
    s_axi_BUS_A_BREADY : IN STD_LOGIC;
    s_axi_BUS_A_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of vec_vec_op_streaming is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "vec_vec_op_streaming_vec_vec_op_streaming,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.291562,HLS_SYN_LAT=29,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=789,HLS_SYN_LUT=2804,HLS_VERSION=2020_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal op : STD_LOGIC_VECTOR (7 downto 0);
    signal op_read_read_fu_86_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal op_read_reg_262 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_vector_scale_fu_92_ap_start : STD_LOGIC;
    signal grp_vector_scale_fu_92_ap_done : STD_LOGIC;
    signal grp_vector_scale_fu_92_ap_idle : STD_LOGIC;
    signal grp_vector_scale_fu_92_ap_ready : STD_LOGIC;
    signal grp_vector_scale_fu_92_vec1_TREADY : STD_LOGIC;
    signal grp_vector_scale_fu_92_vec_out_TDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_vector_scale_fu_92_vec_out_TVALID : STD_LOGIC;
    signal grp_vector_scale_fu_92_vec_out_TREADY : STD_LOGIC;
    signal grp_vector_scale_fu_92_vec_out_TKEEP : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_vector_scale_fu_92_vec_out_TSTRB : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_vector_scale_fu_92_vec_out_TUSER : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_vector_scale_fu_92_vec_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_vector_scale_fu_92_vec_out_TID : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_vector_scale_fu_92_vec_out_TDEST : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_vector_subtract_fu_124_ap_start : STD_LOGIC;
    signal grp_vector_subtract_fu_124_ap_done : STD_LOGIC;
    signal grp_vector_subtract_fu_124_ap_idle : STD_LOGIC;
    signal grp_vector_subtract_fu_124_ap_ready : STD_LOGIC;
    signal grp_vector_subtract_fu_124_vec1_TREADY : STD_LOGIC;
    signal grp_vector_subtract_fu_124_vec2_TREADY : STD_LOGIC;
    signal grp_vector_subtract_fu_124_vec_out_TDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_vector_subtract_fu_124_vec_out_TVALID : STD_LOGIC;
    signal grp_vector_subtract_fu_124_vec_out_TREADY : STD_LOGIC;
    signal grp_vector_subtract_fu_124_vec_out_TKEEP : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_vector_subtract_fu_124_vec_out_TSTRB : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_vector_subtract_fu_124_vec_out_TUSER : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_vector_subtract_fu_124_vec_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_vector_subtract_fu_124_vec_out_TID : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_vector_subtract_fu_124_vec_out_TDEST : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_vector_add_fu_170_ap_start : STD_LOGIC;
    signal grp_vector_add_fu_170_ap_done : STD_LOGIC;
    signal grp_vector_add_fu_170_ap_idle : STD_LOGIC;
    signal grp_vector_add_fu_170_ap_ready : STD_LOGIC;
    signal grp_vector_add_fu_170_vec1_TREADY : STD_LOGIC;
    signal grp_vector_add_fu_170_vec2_TREADY : STD_LOGIC;
    signal grp_vector_add_fu_170_vec_out_TDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_vector_add_fu_170_vec_out_TVALID : STD_LOGIC;
    signal grp_vector_add_fu_170_vec_out_TREADY : STD_LOGIC;
    signal grp_vector_add_fu_170_vec_out_TKEEP : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_vector_add_fu_170_vec_out_TSTRB : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_vector_add_fu_170_vec_out_TUSER : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_vector_add_fu_170_vec_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_vector_add_fu_170_vec_out_TID : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_vector_add_fu_170_vec_out_TDEST : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_vector_add2_fu_216_ap_start : STD_LOGIC;
    signal grp_vector_add2_fu_216_ap_done : STD_LOGIC;
    signal grp_vector_add2_fu_216_ap_idle : STD_LOGIC;
    signal grp_vector_add2_fu_216_ap_ready : STD_LOGIC;
    signal grp_vector_add2_fu_216_vec1_TREADY : STD_LOGIC;
    signal grp_vector_add2_fu_216_vec2_TREADY : STD_LOGIC;
    signal grp_vector_add2_fu_216_vec_out_TDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal grp_vector_add2_fu_216_vec_out_TVALID : STD_LOGIC;
    signal grp_vector_add2_fu_216_vec_out_TREADY : STD_LOGIC;
    signal grp_vector_add2_fu_216_vec_out_TKEEP : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_vector_add2_fu_216_vec_out_TSTRB : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_vector_add2_fu_216_vec_out_TUSER : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_vector_add2_fu_216_vec_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_vector_add2_fu_216_vec_out_TID : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_vector_add2_fu_216_vec_out_TDEST : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_vector_scale_fu_92_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_vector_subtract_fu_124_ap_start_reg : STD_LOGIC := '0';
    signal grp_vector_add_fu_170_ap_start_reg : STD_LOGIC := '0';
    signal grp_vector_add2_fu_216_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal regslice_both_vec_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_predicate_op45_call_state2 : BOOLEAN;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal regslice_both_vec1_V_data_V_U_apdone_blk : STD_LOGIC;
    signal vec1_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal vec1_TVALID_int_regslice : STD_LOGIC;
    signal vec1_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_vec1_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vec1_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal vec1_TKEEP_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_vec1_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec1_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vec1_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal vec1_TSTRB_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_vec1_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec1_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vec1_V_user_V_U_apdone_blk : STD_LOGIC;
    signal vec1_TUSER_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_vec1_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec1_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vec1_V_last_V_U_apdone_blk : STD_LOGIC;
    signal vec1_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_vec1_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec1_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vec1_V_id_V_U_apdone_blk : STD_LOGIC;
    signal vec1_TID_int_regslice : STD_LOGIC_VECTOR (4 downto 0);
    signal regslice_both_vec1_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec1_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vec1_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal vec1_TDEST_int_regslice : STD_LOGIC_VECTOR (5 downto 0);
    signal regslice_both_vec1_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec1_V_dest_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vec2_V_data_V_U_apdone_blk : STD_LOGIC;
    signal vec2_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal vec2_TVALID_int_regslice : STD_LOGIC;
    signal vec2_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_vec2_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vec2_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal vec2_TKEEP_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_vec2_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec2_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vec2_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal vec2_TSTRB_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_vec2_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec2_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vec2_V_user_V_U_apdone_blk : STD_LOGIC;
    signal vec2_TUSER_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_vec2_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec2_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vec2_V_last_V_U_apdone_blk : STD_LOGIC;
    signal vec2_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_vec2_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec2_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vec2_V_id_V_U_apdone_blk : STD_LOGIC;
    signal vec2_TID_int_regslice : STD_LOGIC_VECTOR (4 downto 0);
    signal regslice_both_vec2_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec2_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_vec2_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal vec2_TDEST_int_regslice : STD_LOGIC_VECTOR (5 downto 0);
    signal regslice_both_vec2_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec2_V_dest_V_U_ack_in : STD_LOGIC;
    signal vec_out_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal vec_out_TVALID_int_regslice : STD_LOGIC;
    signal vec_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_vec_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal vec_out_TKEEP_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_vec_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_vec_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal vec_out_TSTRB_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal regslice_both_vec_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_vec_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec_out_V_user_V_U_apdone_blk : STD_LOGIC;
    signal vec_out_TUSER_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_vec_out_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_vec_out_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal vec_out_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_vec_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_vec_out_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec_out_V_id_V_U_apdone_blk : STD_LOGIC;
    signal vec_out_TID_int_regslice : STD_LOGIC_VECTOR (4 downto 0);
    signal regslice_both_vec_out_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_vec_out_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_vec_out_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal vec_out_TDEST_int_regslice : STD_LOGIC_VECTOR (5 downto 0);
    signal regslice_both_vec_out_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_vec_out_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_condition_261 : BOOLEAN;
    signal ap_condition_436 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component vec_vec_op_streaming_vector_scale IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        vec1_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        vec1_TVALID : IN STD_LOGIC;
        vec1_TREADY : OUT STD_LOGIC;
        vec1_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
        vec1_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
        vec1_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
        vec1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        vec1_TID : IN STD_LOGIC_VECTOR (4 downto 0);
        vec1_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
        vec_out_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        vec_out_TVALID : OUT STD_LOGIC;
        vec_out_TREADY : IN STD_LOGIC;
        vec_out_TKEEP : OUT STD_LOGIC_VECTOR (15 downto 0);
        vec_out_TSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
        vec_out_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
        vec_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        vec_out_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
        vec_out_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component vec_vec_op_streaming_vector_subtract IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        vec1_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        vec1_TVALID : IN STD_LOGIC;
        vec1_TREADY : OUT STD_LOGIC;
        vec1_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
        vec1_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
        vec1_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
        vec1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        vec1_TID : IN STD_LOGIC_VECTOR (4 downto 0);
        vec1_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
        vec2_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        vec2_TVALID : IN STD_LOGIC;
        vec2_TREADY : OUT STD_LOGIC;
        vec2_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
        vec2_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
        vec2_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
        vec2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        vec2_TID : IN STD_LOGIC_VECTOR (4 downto 0);
        vec2_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
        vec_out_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        vec_out_TVALID : OUT STD_LOGIC;
        vec_out_TREADY : IN STD_LOGIC;
        vec_out_TKEEP : OUT STD_LOGIC_VECTOR (15 downto 0);
        vec_out_TSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
        vec_out_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
        vec_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        vec_out_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
        vec_out_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component vec_vec_op_streaming_vector_add IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        vec1_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        vec1_TVALID : IN STD_LOGIC;
        vec1_TREADY : OUT STD_LOGIC;
        vec1_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
        vec1_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
        vec1_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
        vec1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        vec1_TID : IN STD_LOGIC_VECTOR (4 downto 0);
        vec1_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
        vec2_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        vec2_TVALID : IN STD_LOGIC;
        vec2_TREADY : OUT STD_LOGIC;
        vec2_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
        vec2_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
        vec2_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
        vec2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        vec2_TID : IN STD_LOGIC_VECTOR (4 downto 0);
        vec2_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
        vec_out_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        vec_out_TVALID : OUT STD_LOGIC;
        vec_out_TREADY : IN STD_LOGIC;
        vec_out_TKEEP : OUT STD_LOGIC_VECTOR (15 downto 0);
        vec_out_TSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
        vec_out_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
        vec_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        vec_out_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
        vec_out_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component vec_vec_op_streaming_vector_add2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        vec1_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        vec1_TVALID : IN STD_LOGIC;
        vec1_TREADY : OUT STD_LOGIC;
        vec1_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
        vec1_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
        vec1_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
        vec1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        vec1_TID : IN STD_LOGIC_VECTOR (4 downto 0);
        vec1_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
        vec2_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        vec2_TVALID : IN STD_LOGIC;
        vec2_TREADY : OUT STD_LOGIC;
        vec2_TKEEP : IN STD_LOGIC_VECTOR (15 downto 0);
        vec2_TSTRB : IN STD_LOGIC_VECTOR (15 downto 0);
        vec2_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
        vec2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        vec2_TID : IN STD_LOGIC_VECTOR (4 downto 0);
        vec2_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
        vec_out_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        vec_out_TVALID : OUT STD_LOGIC;
        vec_out_TREADY : IN STD_LOGIC;
        vec_out_TKEEP : OUT STD_LOGIC_VECTOR (15 downto 0);
        vec_out_TSTRB : OUT STD_LOGIC_VECTOR (15 downto 0);
        vec_out_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
        vec_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        vec_out_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
        vec_out_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component vec_vec_op_streaming_BUS_A_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        op : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component vec_vec_op_streaming_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    BUS_A_s_axi_U : component vec_vec_op_streaming_BUS_A_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_BUS_A_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_BUS_A_DATA_WIDTH)
    port map (
        AWVALID => s_axi_BUS_A_AWVALID,
        AWREADY => s_axi_BUS_A_AWREADY,
        AWADDR => s_axi_BUS_A_AWADDR,
        WVALID => s_axi_BUS_A_WVALID,
        WREADY => s_axi_BUS_A_WREADY,
        WDATA => s_axi_BUS_A_WDATA,
        WSTRB => s_axi_BUS_A_WSTRB,
        ARVALID => s_axi_BUS_A_ARVALID,
        ARREADY => s_axi_BUS_A_ARREADY,
        ARADDR => s_axi_BUS_A_ARADDR,
        RVALID => s_axi_BUS_A_RVALID,
        RREADY => s_axi_BUS_A_RREADY,
        RDATA => s_axi_BUS_A_RDATA,
        RRESP => s_axi_BUS_A_RRESP,
        BVALID => s_axi_BUS_A_BVALID,
        BREADY => s_axi_BUS_A_BREADY,
        BRESP => s_axi_BUS_A_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        op => op,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    grp_vector_scale_fu_92 : component vec_vec_op_streaming_vector_scale
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_vector_scale_fu_92_ap_start,
        ap_done => grp_vector_scale_fu_92_ap_done,
        ap_idle => grp_vector_scale_fu_92_ap_idle,
        ap_ready => grp_vector_scale_fu_92_ap_ready,
        vec1_TDATA => vec1_TDATA_int_regslice,
        vec1_TVALID => vec1_TVALID_int_regslice,
        vec1_TREADY => grp_vector_scale_fu_92_vec1_TREADY,
        vec1_TKEEP => vec1_TKEEP_int_regslice,
        vec1_TSTRB => vec1_TSTRB_int_regslice,
        vec1_TUSER => vec1_TUSER_int_regslice,
        vec1_TLAST => vec1_TLAST_int_regslice,
        vec1_TID => vec1_TID_int_regslice,
        vec1_TDEST => vec1_TDEST_int_regslice,
        vec_out_TDATA => grp_vector_scale_fu_92_vec_out_TDATA,
        vec_out_TVALID => grp_vector_scale_fu_92_vec_out_TVALID,
        vec_out_TREADY => grp_vector_scale_fu_92_vec_out_TREADY,
        vec_out_TKEEP => grp_vector_scale_fu_92_vec_out_TKEEP,
        vec_out_TSTRB => grp_vector_scale_fu_92_vec_out_TSTRB,
        vec_out_TUSER => grp_vector_scale_fu_92_vec_out_TUSER,
        vec_out_TLAST => grp_vector_scale_fu_92_vec_out_TLAST,
        vec_out_TID => grp_vector_scale_fu_92_vec_out_TID,
        vec_out_TDEST => grp_vector_scale_fu_92_vec_out_TDEST);

    grp_vector_subtract_fu_124 : component vec_vec_op_streaming_vector_subtract
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_vector_subtract_fu_124_ap_start,
        ap_done => grp_vector_subtract_fu_124_ap_done,
        ap_idle => grp_vector_subtract_fu_124_ap_idle,
        ap_ready => grp_vector_subtract_fu_124_ap_ready,
        vec1_TDATA => vec1_TDATA_int_regslice,
        vec1_TVALID => vec1_TVALID_int_regslice,
        vec1_TREADY => grp_vector_subtract_fu_124_vec1_TREADY,
        vec1_TKEEP => vec1_TKEEP_int_regslice,
        vec1_TSTRB => vec1_TSTRB_int_regslice,
        vec1_TUSER => vec1_TUSER_int_regslice,
        vec1_TLAST => vec1_TLAST_int_regslice,
        vec1_TID => vec1_TID_int_regslice,
        vec1_TDEST => vec1_TDEST_int_regslice,
        vec2_TDATA => vec2_TDATA_int_regslice,
        vec2_TVALID => vec2_TVALID_int_regslice,
        vec2_TREADY => grp_vector_subtract_fu_124_vec2_TREADY,
        vec2_TKEEP => vec2_TKEEP_int_regslice,
        vec2_TSTRB => vec2_TSTRB_int_regslice,
        vec2_TUSER => vec2_TUSER_int_regslice,
        vec2_TLAST => vec2_TLAST_int_regslice,
        vec2_TID => vec2_TID_int_regslice,
        vec2_TDEST => vec2_TDEST_int_regslice,
        vec_out_TDATA => grp_vector_subtract_fu_124_vec_out_TDATA,
        vec_out_TVALID => grp_vector_subtract_fu_124_vec_out_TVALID,
        vec_out_TREADY => grp_vector_subtract_fu_124_vec_out_TREADY,
        vec_out_TKEEP => grp_vector_subtract_fu_124_vec_out_TKEEP,
        vec_out_TSTRB => grp_vector_subtract_fu_124_vec_out_TSTRB,
        vec_out_TUSER => grp_vector_subtract_fu_124_vec_out_TUSER,
        vec_out_TLAST => grp_vector_subtract_fu_124_vec_out_TLAST,
        vec_out_TID => grp_vector_subtract_fu_124_vec_out_TID,
        vec_out_TDEST => grp_vector_subtract_fu_124_vec_out_TDEST);

    grp_vector_add_fu_170 : component vec_vec_op_streaming_vector_add
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_vector_add_fu_170_ap_start,
        ap_done => grp_vector_add_fu_170_ap_done,
        ap_idle => grp_vector_add_fu_170_ap_idle,
        ap_ready => grp_vector_add_fu_170_ap_ready,
        vec1_TDATA => vec1_TDATA_int_regslice,
        vec1_TVALID => vec1_TVALID_int_regslice,
        vec1_TREADY => grp_vector_add_fu_170_vec1_TREADY,
        vec1_TKEEP => vec1_TKEEP_int_regslice,
        vec1_TSTRB => vec1_TSTRB_int_regslice,
        vec1_TUSER => vec1_TUSER_int_regslice,
        vec1_TLAST => vec1_TLAST_int_regslice,
        vec1_TID => vec1_TID_int_regslice,
        vec1_TDEST => vec1_TDEST_int_regslice,
        vec2_TDATA => vec2_TDATA_int_regslice,
        vec2_TVALID => vec2_TVALID_int_regslice,
        vec2_TREADY => grp_vector_add_fu_170_vec2_TREADY,
        vec2_TKEEP => vec2_TKEEP_int_regslice,
        vec2_TSTRB => vec2_TSTRB_int_regslice,
        vec2_TUSER => vec2_TUSER_int_regslice,
        vec2_TLAST => vec2_TLAST_int_regslice,
        vec2_TID => vec2_TID_int_regslice,
        vec2_TDEST => vec2_TDEST_int_regslice,
        vec_out_TDATA => grp_vector_add_fu_170_vec_out_TDATA,
        vec_out_TVALID => grp_vector_add_fu_170_vec_out_TVALID,
        vec_out_TREADY => grp_vector_add_fu_170_vec_out_TREADY,
        vec_out_TKEEP => grp_vector_add_fu_170_vec_out_TKEEP,
        vec_out_TSTRB => grp_vector_add_fu_170_vec_out_TSTRB,
        vec_out_TUSER => grp_vector_add_fu_170_vec_out_TUSER,
        vec_out_TLAST => grp_vector_add_fu_170_vec_out_TLAST,
        vec_out_TID => grp_vector_add_fu_170_vec_out_TID,
        vec_out_TDEST => grp_vector_add_fu_170_vec_out_TDEST);

    grp_vector_add2_fu_216 : component vec_vec_op_streaming_vector_add2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_vector_add2_fu_216_ap_start,
        ap_done => grp_vector_add2_fu_216_ap_done,
        ap_idle => grp_vector_add2_fu_216_ap_idle,
        ap_ready => grp_vector_add2_fu_216_ap_ready,
        vec1_TDATA => vec1_TDATA_int_regslice,
        vec1_TVALID => vec1_TVALID_int_regslice,
        vec1_TREADY => grp_vector_add2_fu_216_vec1_TREADY,
        vec1_TKEEP => vec1_TKEEP_int_regslice,
        vec1_TSTRB => vec1_TSTRB_int_regslice,
        vec1_TUSER => vec1_TUSER_int_regslice,
        vec1_TLAST => vec1_TLAST_int_regslice,
        vec1_TID => vec1_TID_int_regslice,
        vec1_TDEST => vec1_TDEST_int_regslice,
        vec2_TDATA => vec2_TDATA_int_regslice,
        vec2_TVALID => vec2_TVALID_int_regslice,
        vec2_TREADY => grp_vector_add2_fu_216_vec2_TREADY,
        vec2_TKEEP => vec2_TKEEP_int_regslice,
        vec2_TSTRB => vec2_TSTRB_int_regslice,
        vec2_TUSER => vec2_TUSER_int_regslice,
        vec2_TLAST => vec2_TLAST_int_regslice,
        vec2_TID => vec2_TID_int_regslice,
        vec2_TDEST => vec2_TDEST_int_regslice,
        vec_out_TDATA => grp_vector_add2_fu_216_vec_out_TDATA,
        vec_out_TVALID => grp_vector_add2_fu_216_vec_out_TVALID,
        vec_out_TREADY => grp_vector_add2_fu_216_vec_out_TREADY,
        vec_out_TKEEP => grp_vector_add2_fu_216_vec_out_TKEEP,
        vec_out_TSTRB => grp_vector_add2_fu_216_vec_out_TSTRB,
        vec_out_TUSER => grp_vector_add2_fu_216_vec_out_TUSER,
        vec_out_TLAST => grp_vector_add2_fu_216_vec_out_TLAST,
        vec_out_TID => grp_vector_add2_fu_216_vec_out_TID,
        vec_out_TDEST => grp_vector_add2_fu_216_vec_out_TDEST);

    regslice_both_vec1_V_data_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec1_TDATA,
        vld_in => vec1_TVALID,
        ack_in => regslice_both_vec1_V_data_V_U_ack_in,
        data_out => vec1_TDATA_int_regslice,
        vld_out => vec1_TVALID_int_regslice,
        ack_out => vec1_TREADY_int_regslice,
        apdone_blk => regslice_both_vec1_V_data_V_U_apdone_blk);

    regslice_both_vec1_V_keep_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec1_TKEEP,
        vld_in => vec1_TVALID,
        ack_in => regslice_both_vec1_V_keep_V_U_ack_in,
        data_out => vec1_TKEEP_int_regslice,
        vld_out => regslice_both_vec1_V_keep_V_U_vld_out,
        ack_out => vec1_TREADY_int_regslice,
        apdone_blk => regslice_both_vec1_V_keep_V_U_apdone_blk);

    regslice_both_vec1_V_strb_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec1_TSTRB,
        vld_in => vec1_TVALID,
        ack_in => regslice_both_vec1_V_strb_V_U_ack_in,
        data_out => vec1_TSTRB_int_regslice,
        vld_out => regslice_both_vec1_V_strb_V_U_vld_out,
        ack_out => vec1_TREADY_int_regslice,
        apdone_blk => regslice_both_vec1_V_strb_V_U_apdone_blk);

    regslice_both_vec1_V_user_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec1_TUSER,
        vld_in => vec1_TVALID,
        ack_in => regslice_both_vec1_V_user_V_U_ack_in,
        data_out => vec1_TUSER_int_regslice,
        vld_out => regslice_both_vec1_V_user_V_U_vld_out,
        ack_out => vec1_TREADY_int_regslice,
        apdone_blk => regslice_both_vec1_V_user_V_U_apdone_blk);

    regslice_both_vec1_V_last_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec1_TLAST,
        vld_in => vec1_TVALID,
        ack_in => regslice_both_vec1_V_last_V_U_ack_in,
        data_out => vec1_TLAST_int_regslice,
        vld_out => regslice_both_vec1_V_last_V_U_vld_out,
        ack_out => vec1_TREADY_int_regslice,
        apdone_blk => regslice_both_vec1_V_last_V_U_apdone_blk);

    regslice_both_vec1_V_id_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec1_TID,
        vld_in => vec1_TVALID,
        ack_in => regslice_both_vec1_V_id_V_U_ack_in,
        data_out => vec1_TID_int_regslice,
        vld_out => regslice_both_vec1_V_id_V_U_vld_out,
        ack_out => vec1_TREADY_int_regslice,
        apdone_blk => regslice_both_vec1_V_id_V_U_apdone_blk);

    regslice_both_vec1_V_dest_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec1_TDEST,
        vld_in => vec1_TVALID,
        ack_in => regslice_both_vec1_V_dest_V_U_ack_in,
        data_out => vec1_TDEST_int_regslice,
        vld_out => regslice_both_vec1_V_dest_V_U_vld_out,
        ack_out => vec1_TREADY_int_regslice,
        apdone_blk => regslice_both_vec1_V_dest_V_U_apdone_blk);

    regslice_both_vec2_V_data_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec2_TDATA,
        vld_in => vec2_TVALID,
        ack_in => regslice_both_vec2_V_data_V_U_ack_in,
        data_out => vec2_TDATA_int_regslice,
        vld_out => vec2_TVALID_int_regslice,
        ack_out => vec2_TREADY_int_regslice,
        apdone_blk => regslice_both_vec2_V_data_V_U_apdone_blk);

    regslice_both_vec2_V_keep_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec2_TKEEP,
        vld_in => vec2_TVALID,
        ack_in => regslice_both_vec2_V_keep_V_U_ack_in,
        data_out => vec2_TKEEP_int_regslice,
        vld_out => regslice_both_vec2_V_keep_V_U_vld_out,
        ack_out => vec2_TREADY_int_regslice,
        apdone_blk => regslice_both_vec2_V_keep_V_U_apdone_blk);

    regslice_both_vec2_V_strb_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec2_TSTRB,
        vld_in => vec2_TVALID,
        ack_in => regslice_both_vec2_V_strb_V_U_ack_in,
        data_out => vec2_TSTRB_int_regslice,
        vld_out => regslice_both_vec2_V_strb_V_U_vld_out,
        ack_out => vec2_TREADY_int_regslice,
        apdone_blk => regslice_both_vec2_V_strb_V_U_apdone_blk);

    regslice_both_vec2_V_user_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec2_TUSER,
        vld_in => vec2_TVALID,
        ack_in => regslice_both_vec2_V_user_V_U_ack_in,
        data_out => vec2_TUSER_int_regslice,
        vld_out => regslice_both_vec2_V_user_V_U_vld_out,
        ack_out => vec2_TREADY_int_regslice,
        apdone_blk => regslice_both_vec2_V_user_V_U_apdone_blk);

    regslice_both_vec2_V_last_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec2_TLAST,
        vld_in => vec2_TVALID,
        ack_in => regslice_both_vec2_V_last_V_U_ack_in,
        data_out => vec2_TLAST_int_regslice,
        vld_out => regslice_both_vec2_V_last_V_U_vld_out,
        ack_out => vec2_TREADY_int_regslice,
        apdone_blk => regslice_both_vec2_V_last_V_U_apdone_blk);

    regslice_both_vec2_V_id_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec2_TID,
        vld_in => vec2_TVALID,
        ack_in => regslice_both_vec2_V_id_V_U_ack_in,
        data_out => vec2_TID_int_regslice,
        vld_out => regslice_both_vec2_V_id_V_U_vld_out,
        ack_out => vec2_TREADY_int_regslice,
        apdone_blk => regslice_both_vec2_V_id_V_U_apdone_blk);

    regslice_both_vec2_V_dest_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec2_TDEST,
        vld_in => vec2_TVALID,
        ack_in => regslice_both_vec2_V_dest_V_U_ack_in,
        data_out => vec2_TDEST_int_regslice,
        vld_out => regslice_both_vec2_V_dest_V_U_vld_out,
        ack_out => vec2_TREADY_int_regslice,
        apdone_blk => regslice_both_vec2_V_dest_V_U_apdone_blk);

    regslice_both_vec_out_V_data_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec_out_TDATA_int_regslice,
        vld_in => vec_out_TVALID_int_regslice,
        ack_in => vec_out_TREADY_int_regslice,
        data_out => vec_out_TDATA,
        vld_out => regslice_both_vec_out_V_data_V_U_vld_out,
        ack_out => vec_out_TREADY,
        apdone_blk => regslice_both_vec_out_V_data_V_U_apdone_blk);

    regslice_both_vec_out_V_keep_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec_out_TKEEP_int_regslice,
        vld_in => vec_out_TVALID_int_regslice,
        ack_in => regslice_both_vec_out_V_keep_V_U_ack_in_dummy,
        data_out => vec_out_TKEEP,
        vld_out => regslice_both_vec_out_V_keep_V_U_vld_out,
        ack_out => vec_out_TREADY,
        apdone_blk => regslice_both_vec_out_V_keep_V_U_apdone_blk);

    regslice_both_vec_out_V_strb_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec_out_TSTRB_int_regslice,
        vld_in => vec_out_TVALID_int_regslice,
        ack_in => regslice_both_vec_out_V_strb_V_U_ack_in_dummy,
        data_out => vec_out_TSTRB,
        vld_out => regslice_both_vec_out_V_strb_V_U_vld_out,
        ack_out => vec_out_TREADY,
        apdone_blk => regslice_both_vec_out_V_strb_V_U_apdone_blk);

    regslice_both_vec_out_V_user_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec_out_TUSER_int_regslice,
        vld_in => vec_out_TVALID_int_regslice,
        ack_in => regslice_both_vec_out_V_user_V_U_ack_in_dummy,
        data_out => vec_out_TUSER,
        vld_out => regslice_both_vec_out_V_user_V_U_vld_out,
        ack_out => vec_out_TREADY,
        apdone_blk => regslice_both_vec_out_V_user_V_U_apdone_blk);

    regslice_both_vec_out_V_last_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec_out_TLAST_int_regslice,
        vld_in => vec_out_TVALID_int_regslice,
        ack_in => regslice_both_vec_out_V_last_V_U_ack_in_dummy,
        data_out => vec_out_TLAST,
        vld_out => regslice_both_vec_out_V_last_V_U_vld_out,
        ack_out => vec_out_TREADY,
        apdone_blk => regslice_both_vec_out_V_last_V_U_apdone_blk);

    regslice_both_vec_out_V_id_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec_out_TID_int_regslice,
        vld_in => vec_out_TVALID_int_regslice,
        ack_in => regslice_both_vec_out_V_id_V_U_ack_in_dummy,
        data_out => vec_out_TID,
        vld_out => regslice_both_vec_out_V_id_V_U_vld_out,
        ack_out => vec_out_TREADY,
        apdone_blk => regslice_both_vec_out_V_id_V_U_apdone_blk);

    regslice_both_vec_out_V_dest_V_U : component vec_vec_op_streaming_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => vec_out_TDEST_int_regslice,
        vld_in => vec_out_TVALID_int_regslice,
        ack_in => regslice_both_vec_out_V_dest_V_U_ack_in_dummy,
        data_out => vec_out_TDEST,
        vld_out => regslice_both_vec_out_V_dest_V_U_vld_out,
        ack_out => vec_out_TREADY,
        apdone_blk => regslice_both_vec_out_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_vector_add2_fu_216_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_vector_add2_fu_216_ap_start_reg <= ap_const_logic_0;
            else
                if ((not((op_read_read_fu_86_p2 = ap_const_lv8_0)) and not((op_read_read_fu_86_p2 = ap_const_lv8_1)) and not((op_read_read_fu_86_p2 = ap_const_lv8_2)) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_vector_add2_fu_216_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_vector_add2_fu_216_ap_ready = ap_const_logic_1)) then 
                    grp_vector_add2_fu_216_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_vector_add_fu_170_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_vector_add_fu_170_ap_start_reg <= ap_const_logic_0;
            else
                if (((op_read_read_fu_86_p2 = ap_const_lv8_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_vector_add_fu_170_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_vector_add_fu_170_ap_ready = ap_const_logic_1)) then 
                    grp_vector_add_fu_170_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_vector_scale_fu_92_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_vector_scale_fu_92_ap_start_reg <= ap_const_logic_0;
            else
                if (((op_read_read_fu_86_p2 = ap_const_lv8_2) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_vector_scale_fu_92_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_vector_scale_fu_92_ap_ready = ap_const_logic_1)) then 
                    grp_vector_scale_fu_92_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_vector_subtract_fu_124_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_vector_subtract_fu_124_ap_start_reg <= ap_const_logic_0;
            else
                if (((op_read_read_fu_86_p2 = ap_const_lv8_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_vector_subtract_fu_124_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_vector_subtract_fu_124_ap_ready = ap_const_logic_1)) then 
                    grp_vector_subtract_fu_124_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                op_read_reg_262 <= op;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, regslice_both_vec_out_V_data_V_U_apdone_blk, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((regslice_both_vec_out_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state2_on_subcall_done_assign_proc : process(op_read_reg_262, grp_vector_scale_fu_92_ap_done, grp_vector_subtract_fu_124_ap_done, grp_vector_add_fu_170_ap_done, grp_vector_add2_fu_216_ap_done, ap_predicate_op45_call_state2)
    begin
                ap_block_state2_on_subcall_done <= (((ap_predicate_op45_call_state2 = ap_const_boolean_1) and (grp_vector_add2_fu_216_ap_done = ap_const_logic_0)) or ((grp_vector_scale_fu_92_ap_done = ap_const_logic_0) and (op_read_reg_262 = ap_const_lv8_2)) or ((op_read_reg_262 = ap_const_lv8_0) and (grp_vector_add_fu_170_ap_done = ap_const_logic_0)) or ((op_read_reg_262 = ap_const_lv8_1) and (grp_vector_subtract_fu_124_ap_done = ap_const_logic_0)));
    end process;


    ap_condition_261_assign_proc : process(op_read_reg_262)
    begin
                ap_condition_261 <= (not((op_read_reg_262 = ap_const_lv8_0)) and not((op_read_reg_262 = ap_const_lv8_1)) and not((op_read_reg_262 = ap_const_lv8_2)));
    end process;


    ap_condition_436_assign_proc : process(op_read_reg_262, grp_vector_add2_fu_216_vec_out_TVALID)
    begin
                ap_condition_436 <= (not((op_read_reg_262 = ap_const_lv8_0)) and not((op_read_reg_262 = ap_const_lv8_1)) and not((op_read_reg_262 = ap_const_lv8_2)) and (grp_vector_add2_fu_216_vec_out_TVALID = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state3, regslice_both_vec_out_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_vec_out_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op45_call_state2_assign_proc : process(op_read_reg_262)
    begin
                ap_predicate_op45_call_state2 <= (not((op_read_reg_262 = ap_const_lv8_0)) and not((op_read_reg_262 = ap_const_lv8_1)) and not((op_read_reg_262 = ap_const_lv8_2)));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, regslice_both_vec_out_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_vec_out_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_vector_add2_fu_216_ap_start <= grp_vector_add2_fu_216_ap_start_reg;
    grp_vector_add2_fu_216_vec_out_TREADY <= (vec_out_TREADY_int_regslice and ap_CS_fsm_state2);
    grp_vector_add_fu_170_ap_start <= grp_vector_add_fu_170_ap_start_reg;
    grp_vector_add_fu_170_vec_out_TREADY <= (vec_out_TREADY_int_regslice and ap_CS_fsm_state2);
    grp_vector_scale_fu_92_ap_start <= grp_vector_scale_fu_92_ap_start_reg;
    grp_vector_scale_fu_92_vec_out_TREADY <= (vec_out_TREADY_int_regslice and ap_CS_fsm_state2);
    grp_vector_subtract_fu_124_ap_start <= grp_vector_subtract_fu_124_ap_start_reg;
    grp_vector_subtract_fu_124_vec_out_TREADY <= (vec_out_TREADY_int_regslice and ap_CS_fsm_state2);
    op_read_read_fu_86_p2 <= op;
    vec1_TREADY <= regslice_both_vec1_V_data_V_U_ack_in;

    vec1_TREADY_int_regslice_assign_proc : process(op_read_reg_262, grp_vector_scale_fu_92_vec1_TREADY, grp_vector_subtract_fu_124_vec1_TREADY, grp_vector_add_fu_170_vec1_TREADY, grp_vector_add2_fu_216_vec1_TREADY, ap_CS_fsm_state2, ap_condition_261)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_const_boolean_1 = ap_condition_261)) then 
                vec1_TREADY_int_regslice <= grp_vector_add2_fu_216_vec1_TREADY;
            elsif ((op_read_reg_262 = ap_const_lv8_0)) then 
                vec1_TREADY_int_regslice <= grp_vector_add_fu_170_vec1_TREADY;
            elsif ((op_read_reg_262 = ap_const_lv8_1)) then 
                vec1_TREADY_int_regslice <= grp_vector_subtract_fu_124_vec1_TREADY;
            elsif ((op_read_reg_262 = ap_const_lv8_2)) then 
                vec1_TREADY_int_regslice <= grp_vector_scale_fu_92_vec1_TREADY;
            else 
                vec1_TREADY_int_regslice <= ap_const_logic_0;
            end if;
        else 
            vec1_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    vec2_TREADY <= regslice_both_vec2_V_data_V_U_ack_in;

    vec2_TREADY_int_regslice_assign_proc : process(op_read_reg_262, grp_vector_subtract_fu_124_vec2_TREADY, grp_vector_add_fu_170_vec2_TREADY, grp_vector_add2_fu_216_vec2_TREADY, ap_CS_fsm_state2, ap_condition_261)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_const_boolean_1 = ap_condition_261)) then 
                vec2_TREADY_int_regslice <= grp_vector_add2_fu_216_vec2_TREADY;
            elsif ((op_read_reg_262 = ap_const_lv8_0)) then 
                vec2_TREADY_int_regslice <= grp_vector_add_fu_170_vec2_TREADY;
            elsif ((op_read_reg_262 = ap_const_lv8_1)) then 
                vec2_TREADY_int_regslice <= grp_vector_subtract_fu_124_vec2_TREADY;
            else 
                vec2_TREADY_int_regslice <= ap_const_logic_0;
            end if;
        else 
            vec2_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    vec_out_TDATA_int_regslice_assign_proc : process(op_read_reg_262, grp_vector_scale_fu_92_vec_out_TDATA, grp_vector_scale_fu_92_vec_out_TVALID, grp_vector_subtract_fu_124_vec_out_TDATA, grp_vector_subtract_fu_124_vec_out_TVALID, grp_vector_add_fu_170_vec_out_TDATA, grp_vector_add_fu_170_vec_out_TVALID, grp_vector_add2_fu_216_vec_out_TDATA, ap_CS_fsm_state2, ap_condition_436)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_const_boolean_1 = ap_condition_436)) then 
                vec_out_TDATA_int_regslice <= grp_vector_add2_fu_216_vec_out_TDATA;
            elsif (((op_read_reg_262 = ap_const_lv8_0) and (grp_vector_add_fu_170_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TDATA_int_regslice <= grp_vector_add_fu_170_vec_out_TDATA;
            elsif (((op_read_reg_262 = ap_const_lv8_1) and (grp_vector_subtract_fu_124_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TDATA_int_regslice <= grp_vector_subtract_fu_124_vec_out_TDATA;
            elsif (((op_read_reg_262 = ap_const_lv8_2) and (grp_vector_scale_fu_92_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TDATA_int_regslice <= grp_vector_scale_fu_92_vec_out_TDATA;
            else 
                vec_out_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            vec_out_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    vec_out_TDEST_int_regslice_assign_proc : process(op_read_reg_262, grp_vector_scale_fu_92_vec_out_TVALID, grp_vector_scale_fu_92_vec_out_TDEST, grp_vector_subtract_fu_124_vec_out_TVALID, grp_vector_subtract_fu_124_vec_out_TDEST, grp_vector_add_fu_170_vec_out_TVALID, grp_vector_add_fu_170_vec_out_TDEST, grp_vector_add2_fu_216_vec_out_TDEST, ap_CS_fsm_state2, ap_condition_436)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_const_boolean_1 = ap_condition_436)) then 
                vec_out_TDEST_int_regslice <= grp_vector_add2_fu_216_vec_out_TDEST;
            elsif (((op_read_reg_262 = ap_const_lv8_0) and (grp_vector_add_fu_170_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TDEST_int_regslice <= grp_vector_add_fu_170_vec_out_TDEST;
            elsif (((op_read_reg_262 = ap_const_lv8_1) and (grp_vector_subtract_fu_124_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TDEST_int_regslice <= grp_vector_subtract_fu_124_vec_out_TDEST;
            elsif (((op_read_reg_262 = ap_const_lv8_2) and (grp_vector_scale_fu_92_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TDEST_int_regslice <= grp_vector_scale_fu_92_vec_out_TDEST;
            else 
                vec_out_TDEST_int_regslice <= "XXXXXX";
            end if;
        else 
            vec_out_TDEST_int_regslice <= "XXXXXX";
        end if; 
    end process;


    vec_out_TID_int_regslice_assign_proc : process(op_read_reg_262, grp_vector_scale_fu_92_vec_out_TVALID, grp_vector_scale_fu_92_vec_out_TID, grp_vector_subtract_fu_124_vec_out_TVALID, grp_vector_subtract_fu_124_vec_out_TID, grp_vector_add_fu_170_vec_out_TVALID, grp_vector_add_fu_170_vec_out_TID, grp_vector_add2_fu_216_vec_out_TID, ap_CS_fsm_state2, ap_condition_436)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_const_boolean_1 = ap_condition_436)) then 
                vec_out_TID_int_regslice <= grp_vector_add2_fu_216_vec_out_TID;
            elsif (((op_read_reg_262 = ap_const_lv8_0) and (grp_vector_add_fu_170_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TID_int_regslice <= grp_vector_add_fu_170_vec_out_TID;
            elsif (((op_read_reg_262 = ap_const_lv8_1) and (grp_vector_subtract_fu_124_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TID_int_regslice <= grp_vector_subtract_fu_124_vec_out_TID;
            elsif (((op_read_reg_262 = ap_const_lv8_2) and (grp_vector_scale_fu_92_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TID_int_regslice <= grp_vector_scale_fu_92_vec_out_TID;
            else 
                vec_out_TID_int_regslice <= "XXXXX";
            end if;
        else 
            vec_out_TID_int_regslice <= "XXXXX";
        end if; 
    end process;


    vec_out_TKEEP_int_regslice_assign_proc : process(op_read_reg_262, grp_vector_scale_fu_92_vec_out_TVALID, grp_vector_scale_fu_92_vec_out_TKEEP, grp_vector_subtract_fu_124_vec_out_TVALID, grp_vector_subtract_fu_124_vec_out_TKEEP, grp_vector_add_fu_170_vec_out_TVALID, grp_vector_add_fu_170_vec_out_TKEEP, grp_vector_add2_fu_216_vec_out_TKEEP, ap_CS_fsm_state2, ap_condition_436)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_const_boolean_1 = ap_condition_436)) then 
                vec_out_TKEEP_int_regslice <= grp_vector_add2_fu_216_vec_out_TKEEP;
            elsif (((op_read_reg_262 = ap_const_lv8_0) and (grp_vector_add_fu_170_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TKEEP_int_regslice <= grp_vector_add_fu_170_vec_out_TKEEP;
            elsif (((op_read_reg_262 = ap_const_lv8_1) and (grp_vector_subtract_fu_124_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TKEEP_int_regslice <= grp_vector_subtract_fu_124_vec_out_TKEEP;
            elsif (((op_read_reg_262 = ap_const_lv8_2) and (grp_vector_scale_fu_92_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TKEEP_int_regslice <= grp_vector_scale_fu_92_vec_out_TKEEP;
            else 
                vec_out_TKEEP_int_regslice <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            vec_out_TKEEP_int_regslice <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    vec_out_TLAST_int_regslice_assign_proc : process(op_read_reg_262, grp_vector_scale_fu_92_vec_out_TVALID, grp_vector_scale_fu_92_vec_out_TLAST, grp_vector_subtract_fu_124_vec_out_TVALID, grp_vector_subtract_fu_124_vec_out_TLAST, grp_vector_add_fu_170_vec_out_TVALID, grp_vector_add_fu_170_vec_out_TLAST, grp_vector_add2_fu_216_vec_out_TLAST, ap_CS_fsm_state2, ap_condition_436)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_const_boolean_1 = ap_condition_436)) then 
                vec_out_TLAST_int_regslice <= grp_vector_add2_fu_216_vec_out_TLAST;
            elsif (((op_read_reg_262 = ap_const_lv8_0) and (grp_vector_add_fu_170_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TLAST_int_regslice <= grp_vector_add_fu_170_vec_out_TLAST;
            elsif (((op_read_reg_262 = ap_const_lv8_1) and (grp_vector_subtract_fu_124_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TLAST_int_regslice <= grp_vector_subtract_fu_124_vec_out_TLAST;
            elsif (((op_read_reg_262 = ap_const_lv8_2) and (grp_vector_scale_fu_92_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TLAST_int_regslice <= grp_vector_scale_fu_92_vec_out_TLAST;
            else 
                vec_out_TLAST_int_regslice <= "X";
            end if;
        else 
            vec_out_TLAST_int_regslice <= "X";
        end if; 
    end process;


    vec_out_TSTRB_int_regslice_assign_proc : process(op_read_reg_262, grp_vector_scale_fu_92_vec_out_TVALID, grp_vector_scale_fu_92_vec_out_TSTRB, grp_vector_subtract_fu_124_vec_out_TVALID, grp_vector_subtract_fu_124_vec_out_TSTRB, grp_vector_add_fu_170_vec_out_TVALID, grp_vector_add_fu_170_vec_out_TSTRB, grp_vector_add2_fu_216_vec_out_TSTRB, ap_CS_fsm_state2, ap_condition_436)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_const_boolean_1 = ap_condition_436)) then 
                vec_out_TSTRB_int_regslice <= grp_vector_add2_fu_216_vec_out_TSTRB;
            elsif (((op_read_reg_262 = ap_const_lv8_0) and (grp_vector_add_fu_170_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TSTRB_int_regslice <= grp_vector_add_fu_170_vec_out_TSTRB;
            elsif (((op_read_reg_262 = ap_const_lv8_1) and (grp_vector_subtract_fu_124_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TSTRB_int_regslice <= grp_vector_subtract_fu_124_vec_out_TSTRB;
            elsif (((op_read_reg_262 = ap_const_lv8_2) and (grp_vector_scale_fu_92_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TSTRB_int_regslice <= grp_vector_scale_fu_92_vec_out_TSTRB;
            else 
                vec_out_TSTRB_int_regslice <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            vec_out_TSTRB_int_regslice <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    vec_out_TUSER_int_regslice_assign_proc : process(op_read_reg_262, grp_vector_scale_fu_92_vec_out_TVALID, grp_vector_scale_fu_92_vec_out_TUSER, grp_vector_subtract_fu_124_vec_out_TVALID, grp_vector_subtract_fu_124_vec_out_TUSER, grp_vector_add_fu_170_vec_out_TVALID, grp_vector_add_fu_170_vec_out_TUSER, grp_vector_add2_fu_216_vec_out_TUSER, ap_CS_fsm_state2, ap_condition_436)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_const_boolean_1 = ap_condition_436)) then 
                vec_out_TUSER_int_regslice <= grp_vector_add2_fu_216_vec_out_TUSER;
            elsif (((op_read_reg_262 = ap_const_lv8_0) and (grp_vector_add_fu_170_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TUSER_int_regslice <= grp_vector_add_fu_170_vec_out_TUSER;
            elsif (((op_read_reg_262 = ap_const_lv8_1) and (grp_vector_subtract_fu_124_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TUSER_int_regslice <= grp_vector_subtract_fu_124_vec_out_TUSER;
            elsif (((op_read_reg_262 = ap_const_lv8_2) and (grp_vector_scale_fu_92_vec_out_TVALID = ap_const_logic_1))) then 
                vec_out_TUSER_int_regslice <= grp_vector_scale_fu_92_vec_out_TUSER;
            else 
                vec_out_TUSER_int_regslice <= "XX";
            end if;
        else 
            vec_out_TUSER_int_regslice <= "XX";
        end if; 
    end process;

    vec_out_TVALID <= regslice_both_vec_out_V_data_V_U_vld_out;

    vec_out_TVALID_int_regslice_assign_proc : process(op_read_reg_262, grp_vector_scale_fu_92_vec_out_TVALID, grp_vector_subtract_fu_124_vec_out_TVALID, grp_vector_add_fu_170_vec_out_TVALID, grp_vector_add2_fu_216_vec_out_TVALID, ap_CS_fsm_state2, ap_condition_261)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
            if ((ap_const_boolean_1 = ap_condition_261)) then 
                vec_out_TVALID_int_regslice <= grp_vector_add2_fu_216_vec_out_TVALID;
            elsif ((op_read_reg_262 = ap_const_lv8_0)) then 
                vec_out_TVALID_int_regslice <= grp_vector_add_fu_170_vec_out_TVALID;
            elsif ((op_read_reg_262 = ap_const_lv8_1)) then 
                vec_out_TVALID_int_regslice <= grp_vector_subtract_fu_124_vec_out_TVALID;
            elsif ((op_read_reg_262 = ap_const_lv8_2)) then 
                vec_out_TVALID_int_regslice <= grp_vector_scale_fu_92_vec_out_TVALID;
            else 
                vec_out_TVALID_int_regslice <= ap_const_logic_0;
            end if;
        else 
            vec_out_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
