
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xslda_final.h"

/*
* The configuration table for devices
*/

XSlda_final_Config XSlda_final_ConfigTable[XPAR_XSLDA_FINAL_NUM_INSTANCES] =
{
	{
		XPAR_SLDA_FINAL_0_DEVICE_ID,
		XPAR_SLDA_FINAL_0_S_AXI_CTRL_BASEADDR
	}
};


