// ==============================================================
// Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern "C" void AESL_WRAP_matrix_matrix_mult_streaming (
volatile void* A_0,
volatile void* A_1,
volatile void* A_2,
volatile void* A_3,
volatile void* A_4,
volatile void* A_5,
volatile void* A_6,
volatile void* A_7,
volatile void* A_8,
volatile void* A_9,
volatile void* A_10,
volatile void* A_11,
volatile void* A_12,
volatile void* A_13,
volatile void* A_14,
volatile void* A_15,
volatile void* A_16,
volatile void* A_17,
volatile void* A_18,
volatile void* A_19,
volatile void* A_20,
volatile void* A_21,
volatile void* A_22,
volatile void* A_23,
volatile void* A_24,
volatile void* A_25,
volatile void* A_26,
volatile void* A_27,
volatile void* A_28,
volatile void* A_29,
volatile void* A_30,
volatile void* A_31,
volatile void* B_0,
volatile void* B_1,
volatile void* B_2,
volatile void* B_3,
volatile void* B_4,
volatile void* B_5,
volatile void* B_6,
volatile void* B_7,
volatile void* B_8,
volatile void* B_9,
volatile void* B_10,
volatile void* B_11,
volatile void* B_12,
volatile void* B_13,
volatile void* B_14,
volatile void* B_15,
volatile void* B_16,
volatile void* B_17,
volatile void* B_18,
volatile void* B_19,
volatile void* B_20,
volatile void* B_21,
volatile void* B_22,
volatile void* B_23,
volatile void* B_24,
volatile void* B_25,
volatile void* B_26,
volatile void* B_27,
volatile void* B_28,
volatile void* B_29,
volatile void* B_30,
volatile void* B_31,
hls::stream<struct ap_axis<32, 0, 0, 0 > > (&feature_vector),
volatile void* scores);
